Script started on 2025-07-13 13:07:02-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="106" LINES="42"]
[?2004h]0;ganesh@dknuth: ~/repos/pytorch/issue-158003[01;32mganesh@dknuth[00m:[01;34m~/repos/pytorch/issue-158003[00m$ python run.py
[?2004lTraceback (most recent call last):
  File "/home/ganesh/repos/pytorch/issue-158003/run.py", line 44, in <module>
    c_output = run_test(model, inputs, device, 'inductor')
  File "/home/ganesh/repos/pytorch/issue-158003/run.py", line 38, in run_test
    output = model(*inputs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ganesh/repos/pytorch/issue-158003/run.py", line 17, in forward
    def forward(self, x):
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 901, in forward
    return compiled_fn(full_args)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 81, in g
    return f(*args)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 94, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 105, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 118, in rng_functionalization_wrapper
    return compiled_fw(args)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 864, in __call__
    return self.get_current_callable()(inputs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 611, in run
    return model(new_inputs)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 892, in _run_from_cache
    return compiled_graph.compiled_artifact(inputs)
  File "/tmp/torchinductor_ganesh/y6/cy6igvsvg2xriximbt4qkkroqa6leai7gol7gdoavwddskaczzux.py", line 35, in call
    buf0 = aten.cumsum(arg0_1, 0)
  File "/home/ganesh/.local/lib/python3.10/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.91 GiB. GPU 0 has a total capacity of 11.64 GiB of which 3.67 GiB is free. Including non-PyTorch memory, this process has 7.93 GiB memory in use. Of the allocated memory 7.82 GiB is allocated by PyTorch, and 2.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[?2004h]0;ganesh@dknuth: ~/repos/pytorch/issue-158003[01;32mganesh@dknuth[00m:[01;34m~/repos/pytorch/issue-158003[00m$ exit
[?2004lexit

Script done on 2025-07-13 13:07:23-06:00 [COMMAND_EXIT_CODE="1"]
